"""create brand table

Revision ID: 081d1eeb5974
Revises: ba246ea29902
Create Date: 2025-08-20 17:23:12.447487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '081d1eeb5974'
down_revision: Union[str, Sequence[str], None] = 'ba246ea29902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REGISTERED', 'REJECTED', 'EXPIRED', 'CANCELLED', name='brandstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brands')
    # ### end Alembic commands ###
