"""update bran table set created by field

Revision ID: 4c3079a3e835
Revises: b40b6d83542e
Create Date: 2025-08-20 18:42:47.672186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c3079a3e835'
down_revision: Union[str, Sequence[str], None] = 'b40b6d83542e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar columna como nullable primero
    op.add_column('brands', sa.Column('created_by', sa.Integer(), nullable=True))
    
    # Crear la foreign key
    op.create_foreign_key(
        'fk_brands_created_by_users', 
        'brands', 'users', 
        ['created_by'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_brands_created_by_users', 'brands', type_='foreignkey')
    op.drop_column('brands', 'created_by')
    # ### end Alembic commands ###
